"""
make_fig4.py
============
Generates Fig 4: Forward vs. reverse asymmetry reveals directional structure.

Panel A: Side-by-side forward and reverse Flow Trees for two example nodes
         — one symmetric hub, one directional funnel.
Panel B: Scatter plot of forward depth vs. reverse depth (and diameter) per node,
         with landmark nodes highlighted.

Run from the mazedyn directory with the mazedyn-test conda environment:
    conda activate mazedyn-test
    python make_fig4.py

Requires: figures/fig3_cache.pkl (generated by make_fig3.py)
"""

import os
import pickle

import matplotlib
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np
import pandas as pd
from flow_tree_utils import (
    generate_flow_tree_from_trajs,
    plot_flow_tree,
)
from wordfreq import zipf_frequency

# ── Style ────────────────────────────────────────────────────────────────────
matplotlib.rcParams.update(
    {
        "font.family": "sans-serif",
        "font.size": 8,
        "axes.labelsize": 8,
        "axes.titlesize": 9,
        "xtick.labelsize": 7,
        "ytick.labelsize": 7,
        "legend.fontsize": 7,
        "figure.dpi": 300,
        "axes.spines.top": False,
        "axes.spines.right": False,
        "axes.linewidth": 0.8,
    }
)

HUMAN_COLOR = "#E05C5C"
LANDMARK_COLOR = "#E05C5C"
NON_LM_COLOR = "#AAAAAA"
HIGHLIGHT_COLOR = "#F0A500"

os.makedirs("figures", exist_ok=True)
CACHE_FILE = "figures/fig3_cache.pkl"

# ── 1. Load data ─────────────────────────────────────────────────────────────
print("Loading data...")
data_path = "data/wikispeedia_paths-and-graph"

article_names = []
with open(f"{data_path}/articles.tsv") as f:
    for line in f:
        line = line.strip()
        if not line or line[0] == "#":
            continue
        article_names.append(line)

edges_df = pd.read_csv(
    f"{data_path}/links.tsv",
    names=["linkSource", "linkTarget"],
    sep="\t",
    skiprows=13,
)
wikiG = nx.DiGraph()
wikiG.add_edges_from(zip(edges_df.linkSource, edges_df.linkTarget))


def get_nth_article(s, n):
    return s.split(";")[n]


def process_path(path):
    assert ";<" * 23 not in path
    for i in range(21, 0, -1):
        seq = "<" + ";<" * i
        if seq in path:
            path = path.replace(seq, f"<{i + 1}")
    nodes = []
    for i, node in enumerate(path.split(";")):
        if "<" in node:
            bk = 1 if node == "<" else int(node[1:])
            node = nodes[i - bk - 1]
        nodes.append(node)
    return nodes


finished_df = pd.read_csv(
    f"{data_path}/paths_finished.tsv",
    names=["hashedIpAddress", "timestamp", "durationInSec", "path", "rating"],
    sep="\t",
    skiprows=16,
)
finished_df["StartAt"] = finished_df["path"].apply(lambda x: get_nth_article(x, 0))
finished_df["EndAt"] = finished_df["path"].apply(lambda x: get_nth_article(x, -1))
finished_df["finished"] = True

unfinished_df = pd.read_csv(
    f"{data_path}/paths_unfinished.tsv",
    names=["hashedIpAddress", "timestamp", "durationInSec", "path", "target", "type"],
    sep="\t",
    skiprows=17,
)
unfinished_df["StartAt"] = unfinished_df["path"].apply(lambda x: get_nth_article(x, 0))
unfinished_df["EndAt"] = unfinished_df["target"]
unfinished_df["finished"] = False

trajs_df = pd.concat([finished_df, unfinished_df]).reset_index(drop=True)
trajs_df = trajs_df.drop_duplicates(subset=["hashedIpAddress", "StartAt", "target"])
trajs_df["traj"] = trajs_df["path"].apply(process_path)
print(f"  Trajectories: {len(trajs_df)}")

# ── 2. Node properties ───────────────────────────────────────────────────────
node_counts, node_outdegrees, node_zipf = {}, {}, {}
STOP_WORDS = {"a", "an", "the", "and", "for", "of"}
for traj in trajs_df.traj:
    for n in traj:
        node_counts[n] = node_counts.get(n, 0) + 1
for n in node_counts:
    if n in wikiG:
        node_outdegrees[n] = wikiG.out_degree(n)
        words = [w for w in n.split("_") if w.lower() not in STOP_WORDS]
        node_zipf[n] = np.mean([zipf_frequency(w, "en") for w in words]) if words else 0


def top_k(d, k, restrict=None):
    keys = list(restrict or d.keys())
    return set(sorted(keys, key=lambda x: d.get(x, 0), reverse=True)[:k])


most_common_nodes = top_k(node_counts, 500)
most_common_nodes.discard("Wikipedia_Text_of_the_GNU_Free_Documentation_License")
outdegree_landmarks = top_k(node_outdegrees, 50, restrict=most_common_nodes)
player_landmarks = top_k(node_counts, 50, restrict=most_common_nodes)
all_landmarks = outdegree_landmarks | player_landmarks

MIN_PATH = 6
TRAJ_PER_TREE = 13
K_FOLD = 5
rev_wikiG = wikiG.reverse()


# ── 3. Flow tree helpers ─────────────────────────────────────────────────────
def make_traj_dict(nodes):
    d = {n: [] for n in nodes}
    for traj in trajs_df.traj:
        for i in range(len(traj) - MIN_PATH - 1):
            if traj[i] in nodes:
                d[traj[i]].append(traj[i : i + MIN_PATH])
    return d


def make_rev_traj_dict(nodes):
    d = {n: [] for n in nodes}
    for traj in trajs_df.traj:
        for i in range(MIN_PATH, len(traj)):
            if traj[i] in nodes:
                d[traj[i]].append(list(reversed(traj[i - MIN_PATH : i])))
    return d


def sample_trees(traj_dict, graph, k_fold=K_FOLD, n=TRAJ_PER_TREE):
    result = {}
    for node, trajs in traj_dict.items():
        human_trees = []
        for _ in range(k_fold):
            sampled = (
                trajs
                if len(trajs) <= n
                else [trajs[i] for i in np.random.choice(len(trajs), n, replace=False)]
            )
            if not sampled:
                continue
            G = generate_flow_tree_from_trajs(sampled, END_NODE="1")
            G = nx.relabel.convert_node_labels_to_integers(G, ordering="default")
            human_trees.append(G)
        result[node] = {"human": human_trees}
    return result


def tree_depth(G, root=0):
    if G.number_of_nodes() < 2:
        return 0
    depths = nx.single_source_shortest_path_length(G, root)
    return max(depths.values())


def tree_diameter(G):
    if G.number_of_nodes() < 2:
        return 0
    try:
        return nx.diameter(G)
    except Exception:
        return 0


# ── 4. Compute or load ───────────────────────────────────────────────────────
if os.path.exists(CACHE_FILE):
    print(f"Loading cached flow trees from {CACHE_FILE}...")
    with open(CACHE_FILE, "rb") as f:
        cache = pickle.load(f)
    ft_dict = cache["ft_dict"]
    rev_ft_dict = cache["rev_ft_dict"]
else:
    print("Computing flow trees (run make_fig3.py first to cache)...")
    td = make_traj_dict(most_common_nodes)
    rev_td = make_rev_traj_dict(most_common_nodes)
    ft_dict = sample_trees(td, wikiG)
    rev_ft_dict = sample_trees(rev_td, rev_wikiG)
    with open(CACHE_FILE, "wb") as f:
        pickle.dump({"ft_dict": ft_dict, "rev_ft_dict": rev_ft_dict}, f)

# ── 5. Build per-node forward/reverse metric arrays ─────────────────────────
print("Computing per-node forward/reverse metrics...")
records = []
for node in most_common_nodes:
    fwd_trees = ft_dict.get(node, {}).get("human", [])
    rev_trees = rev_ft_dict.get(node, {}).get("human", [])
    if not fwd_trees or not rev_trees:
        continue
    fwd_depths = [tree_depth(G) for G in fwd_trees]
    rev_depths = [tree_depth(G) for G in rev_trees]
    fwd_diameters = [tree_diameter(G) for G in fwd_trees]
    rev_diameters = [tree_diameter(G) for G in rev_trees]
    fwd_bfs = [
        np.mean([FT.degree(node) for node in FT.nodes() if FT.degree(node) != 1])
        for FT in fwd_trees
    ]
    rev_bfs = [
        np.mean([FT.degree(node) for node in FT.nodes() if FT.degree(node) != 1])
        for FT in rev_trees
    ]
    records.append(
        {
            "node": node,
            "fwd_depth": np.mean(fwd_depths),
            "rev_depth": np.mean(rev_depths),
            "fwd_diameter": np.mean(fwd_diameters),
            "rev_diameter": np.mean(rev_diameters),
            "fwd_bf": np.mean(fwd_bfs),
            "rev_bf": np.mean(rev_bfs),
            "is_landmark": node in all_landmarks,
            "is_outd_lm": node in outdegree_landmarks,
            "is_player_lm": node in player_landmarks,
        }
    )
df = pd.DataFrame(records)
print(f"  {len(df)} nodes with both forward and reverse trees")

# ── 6. Fig 4A: Three example node types ─────────────────────────────────────
print("Making Fig 4A...")

df["asym_depth_score"] = np.abs(df["fwd_depth"] - df["rev_depth"])
df["asym_bf_score"] = np.abs(df["fwd_bf"] - df["rev_bf"])
df["mean_bf"] = (df["fwd_bf"] + df["rev_bf"]) / 2
df["mean_depth"] = (df["fwd_depth"] + df["rev_depth"]) / 2

# Symmetric fan: high BF in both directions, close to diagonal
# (wide and shallow both ways — typical landmark hub)
fan_cands = df[df["mean_bf"] > df["mean_bf"].quantile(0.75)].sort_values(
    "asym_bf_score"
)
fan_node = fan_cands.iloc[0]["node"]

# Symmetric hallway: high depth both ways, close to diagonal
# (narrow and deep both ways — a bottleneck / sequential node)
hall_cands = df[df["mean_depth"] > df["mean_depth"].quantile(0.75)].sort_values(
    "asym_depth_score"
)
hall_node = hall_cands.iloc[0]["node"]

# Asymmetric: large difference between forward and reverse depth
asym_node = df.sort_values("asym_depth_score", ascending=False).iloc[0]["node"]

print(f"  Symmetric fan:      {fan_node}")
print(f"  Symmetric hallway:  {hall_node}")
print(f"  Asymmetric:         {asym_node}")

ROW_CONFIGS = [
    (fan_node, "symmetric\nfan", "#5C7A5C"),  # muted green
    (hall_node, "symmetric\nhallway", "#5B6FA8"),  # muted blue
    (asym_node, "asymmetric", "#8B5E5E"),  # muted brick
]

fig_a, axes_a = plt.subplots(3, 2, figsize=(4.8, 6.5))
fig_a.subplots_adjust(hspace=0.38, wspace=0.12, top=0.93, left=0.22, right=0.97)

# Column headers
for col_i, col_title in enumerate(["Forward", "Reverse"]):
    axes_a[0][col_i].set_title(col_title, fontsize=8.5, pad=5, color="#333")

for row_i, (node, row_label, row_col) in enumerate(ROW_CONFIGS):
    fwd_trees = ft_dict.get(node, {}).get("human", [])
    rev_trees = rev_ft_dict.get(node, {}).get("human", [])
    node_label = node.replace("_", " ")

    for col_i, trees in enumerate([fwd_trees, rev_trees]):
        ax = axes_a[row_i][col_i]
        ax.axis("off")
        if trees:
            plot_flow_tree(trees[0], node_label, ax, just_edges=True, no_title=True)
        else:
            ax.text(
                0.5,
                0.5,
                "—",
                transform=ax.transAxes,
                ha="center",
                fontsize=9,
                color="#aaa",
            )

    # Row label on the left
    axes_a[row_i][0].text(
        -0.28,
        0.5,
        row_label,
        transform=axes_a[row_i][0].transAxes,
        fontsize=8,
        va="center",
        ha="right",
        color=row_col,
        linespacing=1.4,
    )
    # Article name below each pair, centred
    axes_a[row_i][0].text(
        1.05,
        -0.06,
        node_label,
        transform=axes_a[row_i][0].transAxes,
        fontsize=6,
        ha="center",
        va="top",
        color="#777",
        style="italic",
    )

plt.savefig("figures/fig4A.pdf", bbox_inches="tight")
plt.savefig("figures/fig4A.png", bbox_inches="tight", dpi=300)
print("  Saved figures/fig4A.pdf")

# ── 7. Fig 4B: Scatter – forward vs reverse depth + diameter ─────────────────
print("Making Fig 4B...")

fig_b, axes_b = plt.subplots(1, 2, figsize=(6.0, 3.2))
fig_b.subplots_adjust(wspace=0.38, left=0.10, right=0.97, top=0.90, bottom=0.16)

metric_pairs = [
    # ("fwd_depth",    "rev_depth",    "Depth"),
    ("fwd_bf", "rev_bf", "Branching Factor"),
    ("fwd_diameter", "rev_diameter", "Diameter"),
]

for ax, (x_col, y_col, metric_name) in zip(axes_b, metric_pairs):
    non_lm = df[~df["is_landmark"]]
    lm_out = df[df["is_outd_lm"]]
    lm_ply = df[df["is_player_lm"] & ~df["is_outd_lm"]]

    ax.scatter(
        non_lm[x_col],
        non_lm[y_col],
        s=12,
        alpha=0.35,
        color=NON_LM_COLOR,
        linewidths=0,
        zorder=2,
        label="Non-landmark",
    )
    ax.scatter(
        lm_out[x_col],
        lm_out[y_col],
        s=30,
        alpha=0.85,
        color=LANDMARK_COLOR,
        edgecolors="white",
        linewidths=0.4,
        zorder=4,
        marker="*",
        label="Structural landmark",
    )
    ax.scatter(
        lm_ply[x_col],
        lm_ply[y_col],
        s=22,
        alpha=0.70,
        color=HIGHLIGHT_COLOR,
        edgecolors="white",
        linewidths=0.4,
        zorder=3,
        marker="D",
        label="Data-driven landmark",
    )

    # identity line
    all_vals = pd.concat([df[x_col], df[y_col]])
    lo, hi = all_vals.min() * 0.9, all_vals.max() * 1.08
    ax.plot(
        [lo, hi],
        [lo, hi],
        "--",
        color="#999",
        lw=0.9,
        zorder=1,
        label="Diagonal (symmetric)",
    )
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect("equal")

    ax.set_xlabel(f"Forward {metric_name.lower()}", labelpad=3)
    ax.set_ylabel(f"Reverse {metric_name.lower()}", labelpad=3)
    ax.set_title(metric_name, fontsize=9)

    # annotate a few landmark outliers
    top_asym = df[df["is_landmark"]].nlargest(3, "asym_bf_score")
    for _, row in top_asym.iterrows():
        lbl = row["node"].replace("_", " ")
        ax.annotate(
            lbl,
            (row[x_col], row[y_col]),
            textcoords="offset points",
            xytext=(4, 4),
            fontsize=5.5,
            color="#333",
            alpha=0.8,
        )

# shared legend
handles, labels = axes_b[1].get_legend_handles_labels()
fig_b.legend(
    handles,
    labels,
    loc="lower center",
    ncol=4,
    frameon=False,
    fontsize=6.5,
    bbox_to_anchor=(0.53, -0.07),
)

plt.savefig("figures/fig4B.pdf", bbox_inches="tight")
plt.savefig("figures/fig4B.png", bbox_inches="tight", dpi=300)
print("  Saved figures/fig4B.pdf")

# ── 8. Fig 4C: Scatter – human vs random, forward vs reverse ─────────────────
print("Making Fig 4C...")

import matplotlib.lines as mlines
import matplotlib.transforms as transforms
from matplotlib.patches import Ellipse


def confidence_ellipse(x, y, ax, n_std=1.5, **kwargs):
    """Draw a covariance confidence ellipse for data x, y."""
    if len(x) < 3:
        return
    cov = np.cov(x, y)
    pearson = cov[0, 1] / np.sqrt(cov[0, 0] * cov[1, 1])
    rx = np.sqrt(1 + pearson)
    ry = np.sqrt(1 - pearson)
    ellipse = Ellipse((0, 0), width=rx * 2, height=ry * 2, **kwargs)
    sx = np.sqrt(cov[0, 0]) * n_std
    sy = np.sqrt(cov[1, 1]) * n_std
    t = (
        transforms.Affine2D()
        .rotate_deg(45)
        .scale(sx, sy)
        .translate(np.mean(x), np.mean(y))
    )
    ellipse.set_transform(t + ax.transData)
    return ax.add_patch(ellipse)


# Build per-node random records
random_records = []
for node in most_common_nodes:
    fwd_trees = ft_dict.get(node, {}).get("random", [])
    rev_trees = rev_ft_dict.get(node, {}).get("random", [])
    if not fwd_trees or not rev_trees:
        continue
    fwd_depths = [tree_depth(G) for G in fwd_trees]
    rev_depths = [tree_depth(G) for G in rev_trees]
    fwd_diameters = [tree_diameter(G) for G in fwd_trees]
    rev_diameters = [tree_diameter(G) for G in rev_trees]
    fwd_bfs = [
        np.mean([FT.degree(n) for n in FT.nodes() if FT.degree(n) != 1])
        for FT in fwd_trees
    ]
    rev_bfs = [
        np.mean([FT.degree(n) for n in FT.nodes() if FT.degree(n) != 1])
        for FT in rev_trees
    ]
    random_records.append(
        {
            "node": node,
            "fwd_depth": np.mean(fwd_depths),
            "rev_depth": np.mean(rev_depths),
            "fwd_diameter": np.mean(fwd_diameters),
            "rev_diameter": np.mean(rev_diameters),
            "fwd_bf": np.mean(fwd_bfs),
            "rev_bf": np.mean(rev_bfs),
            "is_landmark": node in all_landmarks,
            "is_outd_lm": node in outdegree_landmarks,
            "is_player_lm": node in player_landmarks,
        }
    )
df_rand = pd.DataFrame(random_records)
print(f"  {len(df_rand)} nodes with random forward+reverse trees")

# Muted palette — less saturated than default
C_HUMAN = "#B5403E"  # brick red
C_RAND = "#3A6592"  # slate blue
C_DIAG = "#BBBBBB"

metric_pairs_c = [
    ("fwd_bf", "rev_bf", "branching factor"),
    ("fwd_diameter", "rev_diameter", "diameter"),
]

fig_c, axes_c = plt.subplots(1, 2, figsize=(6.0, 3.2))
fig_c.subplots_adjust(wspace=0.45, left=0.11, right=0.97, top=0.87, bottom=0.17)

for ax, (x_col, y_col, metric_name) in zip(axes_c, metric_pairs_c):
    # ── raw scatter: all nodes, both walker types, very faint
    ax.scatter(
        df[x_col], df[y_col], s=7, alpha=0.18, color=C_HUMAN, linewidths=0, zorder=2
    )
    ax.scatter(
        df_rand[x_col],
        df_rand[y_col],
        s=7,
        alpha=0.18,
        color=C_RAND,
        linewidths=0,
        zorder=2,
    )

    # ── landmark points, slightly larger
    lm_h = df[df["is_outd_lm"]]
    lm_r = df_rand[df_rand["is_outd_lm"]]
    ax.scatter(
        lm_h[x_col],
        lm_h[y_col],
        s=22,
        alpha=0.75,
        color=C_HUMAN,
        linewidths=0,
        zorder=4,
    )
    ax.scatter(
        lm_r[x_col], lm_r[y_col], s=22, alpha=0.75, color=C_RAND, linewidths=0, zorder=4
    )

    # ── confidence ellipses (1.5σ) for each group
    for dframe, col, lw, ls in [
        (df, C_HUMAN, 1.4, "-"),
        (df_rand, C_RAND, 1.4, "-"),
        (df[df["is_outd_lm"]], C_HUMAN, 1.2, "--"),
        (df_rand[df_rand["is_outd_lm"]], C_RAND, 1.2, "--"),
    ]:
        _valid = dframe[[x_col, y_col]].dropna()
        x_data = _valid[x_col].values
        y_data = _valid[y_col].values
        confidence_ellipse(
            x_data,
            y_data,
            ax,
            n_std=1.5,
            edgecolor=col,
            facecolor="none",
            linewidth=lw,
            linestyle=ls,
            zorder=6,
        )

    # ── diagonal reference
    all_vals = pd.concat([df[x_col], df[y_col], df_rand[x_col], df_rand[y_col]])
    lo = all_vals.min() - 0.15 * all_vals.std()
    hi = all_vals.max() + 0.25 * all_vals.std()
    ax.plot([lo, hi], [lo, hi], color=C_DIAG, lw=0.9, zorder=1)
    ax.set_xlim(lo, hi)
    ax.set_ylim(lo, hi)
    ax.set_aspect("equal")

    ax.set_xlabel(f"forward {metric_name}", labelpad=4, fontsize=8)
    ax.set_ylabel(f"reverse {metric_name}", labelpad=4, fontsize=8)
    ax.set_title(metric_name.title(), fontsize=9, pad=5)
    ax.tick_params(labelsize=7)

# Simple, honest legend
leg_elements = [
    mlines.Line2D([0], [0], color=C_HUMAN, lw=1.4, label="human (all nodes)"),
    mlines.Line2D([0], [0], color=C_RAND, lw=1.4, label="random (all nodes)"),
    mlines.Line2D([0], [0], color=C_HUMAN, lw=1.2, ls="--", label="human landmark"),
    mlines.Line2D([0], [0], color=C_RAND, lw=1.2, ls="--", label="random landmark"),
    mlines.Line2D([0], [0], color=C_DIAG, lw=0.9, label="symmetric (diagonal)"),
]
fig_c.legend(
    handles=leg_elements,
    loc="lower center",
    ncol=3,
    frameon=False,
    fontsize=6.5,
    bbox_to_anchor=(0.5, -0.13),
    handlelength=1.8,
)

plt.savefig("figures/fig4C.pdf", bbox_inches="tight")
plt.savefig("figures/fig4C.png", bbox_inches="tight", dpi=300)
print("  Saved figures/fig4C.pdf")
print("\nDone! Check the figures/ directory.")
